//! The Sentry types tinysweeper is willing to hold in memory at all.
//!
//! **These structs are the allow-list.** Not a filter applied to a parsed
//! payload — the parse itself. Serde reads the fields declared here and ignores
//! everything else in the response, so `request.data`, `request.cookies`,
//! `request.headers`, `user`, `contexts`, `extra`, breadcrumb payloads and
//! frame-local `vars` are never deserialized, never bound to a variable, and
//! never reachable from any later stage. There is no code path that *could*
//! promote them, which is a stronger guarantee than a code path that chooses
//! not to.
//!
//! This is also why none of these types carry `deny_unknown_fields`. Sentry
//! adds fields; a strict parse would turn every schema addition into a hard
//! failure, and the pressure that creates is to relax the parse. Ignoring the
//! unknown *is* the desired behaviour here: a field we have never heard of is
//! a field we do not promote.
//!
//! Numbers arrive inconsistently — Sentry sends issue `count` as a decimal
//! string and `userCount` as a number — so counts go through
//! [`de_count`], which accepts either and refuses anything else.
//!
//! Everything here is still **unscrubbed**. An exception message can carry a
//! credential someone logged, so nothing in this module may reach GitHub, a
//! log line, or a hash without going through [`crate::sentry::redact`] first.

use serde::{Deserialize, Deserializer, Serialize};

/// One unresolved Sentry issue, as listed by
/// `GET /projects/{org}/{project}/issues/`.
///
/// Unscrubbed. See the module docs.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RawIssue {
    /// Sentry's numeric issue id, as a string. Used to fetch the latest event
    /// and to annotate or resolve; never promoted.
    #[serde(default)]
    pub id: String,
    /// The human-readable short id (`API-1A2B`) that appears in the dedupe
    /// marker and in the promoted title.
    #[serde(default)]
    pub short_id: String,
    /// Where Sentry believes the error came from.
    #[serde(default)]
    pub culprit: Option<String>,
    /// `error`, `warning`, `fatal`, …
    #[serde(default)]
    pub level: Option<String>,
    /// The Sentry UI link. Generated by Sentry, not captured from the
    /// process, which is why it is safe to promote.
    #[serde(default)]
    pub permalink: Option<String>,
    /// How many times the issue has been seen.
    #[serde(default, deserialize_with = "de_count")]
    pub count: u64,
    /// How many distinct users it has affected.
    #[serde(default, deserialize_with = "de_count")]
    pub user_count: u64,
    /// The exception type and value, as Sentry summarises them.
    #[serde(default)]
    pub metadata: RawMetadata,
}

/// The `metadata` block of an issue: the exception type and message.
///
/// Sentry also puts `filename`, `function` and — for some platforms — richer
/// context in here. Only these two are declared, so only these two are read.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
pub struct RawMetadata {
    /// The exception class, e.g. `TypeError`.
    #[serde(default, rename = "type")]
    pub kind: Option<String>,
    /// The exception message.
    #[serde(default)]
    pub value: Option<String>,
}

/// The latest event for an issue, as returned by
/// `GET /issues/{id}/events/latest/`.
///
/// This is the most dangerous payload in the product — it is captured from a
/// running production process — which is why so little of it is declared. The
/// entire request, user, contexts, extra and breadcrumb surface is absent by
/// omission.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct RawEvent {
    /// The transaction or route name.
    #[serde(default)]
    pub transaction: Option<String>,
    /// The release the event was seen on.
    #[serde(default)]
    pub release: Option<RawRelease>,
    /// The event's entries. Only `exception` entries are read, and only for
    /// their frame file/function/line.
    #[serde(default)]
    pub entries: Vec<RawEntry>,
}

/// A release, which Sentry sends either as a bare version string or as an
/// object carrying one.
#[derive(Debug, Clone, Deserialize)]
#[serde(untagged)]
pub enum RawRelease {
    /// `"release": "1.2.3"`.
    Version(String),
    /// `"release": { "version": "1.2.3", … }`.
    Object {
        /// The version string.
        #[serde(default)]
        version: Option<String>,
    },
}

impl RawRelease {
    /// The version string, whichever shape it arrived in.
    pub fn version(&self) -> Option<&str> {
        match self {
            Self::Version(version) => Some(version.as_str()),
            Self::Object { version } => version.as_deref(),
        }
    }
}

/// One entry in an event. `data` is deliberately typed as the *exception*
/// shape with every field optional, so a `breadcrumbs` or `request` entry
/// deserializes into an empty husk rather than into anything readable.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct RawEntry {
    /// The entry kind. Only `exception` is read.
    #[serde(default, rename = "type")]
    pub kind: String,
    /// The entry payload.
    #[serde(default)]
    pub data: RawEntryData,
}

/// The payload of an `exception` entry.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct RawEntryData {
    /// The exception chain.
    #[serde(default)]
    pub values: Vec<RawExceptionValue>,
}

/// One exception in the chain.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct RawExceptionValue {
    /// Its stack trace, when it has one.
    #[serde(default)]
    pub stacktrace: Option<RawStacktrace>,
}

/// A stack trace: frames and nothing else.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct RawStacktrace {
    /// The frames, innermost last (Sentry's order).
    #[serde(default)]
    pub frames: Vec<RawFrame>,
}

/// One stack frame.
///
/// **`vars`, `context_line`, `pre_context` and `post_context` are deliberately
/// absent.** Frame locals are where the personal data in a stack trace
/// actually is: a captured `password`, a session object, a decoded JWT. A
/// stack trace worth promoting is file, function and line — nothing else.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct RawFrame {
    /// The source file.
    #[serde(default)]
    pub filename: Option<String>,
    /// The function or method name.
    #[serde(default)]
    pub function: Option<String>,
    /// The line number.
    #[serde(default)]
    pub lineno: Option<u32>,
}

/// Accept a count Sentry sends as either a JSON number or a decimal string.
///
/// Issue `count` is a string and `userCount` is a number in the same response
/// object, so one of the two would fail a strict parse — and a filter that
/// errors on a live payload is a filter someone deletes.
fn de_count<'de, D: Deserializer<'de>>(deserializer: D) -> Result<u64, D::Error> {
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum Count {
        Number(u64),
        Text(String),
    }

    match Option::<Count>::deserialize(deserializer)? {
        None => Ok(0),
        Some(Count::Number(n)) => Ok(n),
        // A count that does not parse is reported as zero rather than as an
        // error: it fails *closed* through the `min_events` / `min_users`
        // gates, so a malformed payload cannot promote anything.
        Some(Count::Text(text)) => Ok(text.trim().parse().unwrap_or(0)),
    }
}

/// One promotable stack frame: file, function, line.
///
/// Constructed only by [`crate::sentry::redact`], so the strings are already
/// scrubbed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SafeFrame {
    /// The source file.
    pub filename: String,
    /// The function or method name.
    pub function: String,
    /// The line number, when the frame reported one.
    pub lineno: Option<u32>,
}

/// A Sentry issue reduced to exactly what may be written to GitHub.
///
/// Every string has been through [`crate::sentry::redact::scrub_text`] and the
/// whole struct is size-capped. Its serialized key set is asserted against
/// [`crate::sentry::redact::ALLOWED_FIELDS`] by a test, so a field added here
/// without being argued for on the allow-list fails the build's test run.
///
/// ## Why it cannot be built by hand
///
/// The private `scrubbed` token means struct-literal construction is
/// impossible outside [`crate::sentry::redact`], where the only constructor
/// lives. Reading the fields stays free. Without it, a future caller could
/// assemble a `SafeIssue` from raw strings and every guarantee in this module
/// would become a convention.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SafeIssue {
    /// Sentry's short id, e.g. `API-1A2B`.
    pub short_id: String,
    /// The project slug the issue belongs to.
    pub project: String,
    /// The exception class.
    pub kind: String,
    /// The exception message.
    pub value: String,
    /// Sentry's culprit string.
    pub culprit: String,
    /// The transaction or route.
    pub transaction: String,
    /// `error`, `warning`, `fatal`, …
    pub level: String,
    /// How many times it has been seen.
    pub count: u64,
    /// How many users it has affected.
    pub user_count: u64,
    /// The release it was last seen on.
    pub release: String,
    /// File/function/line for each promotable frame.
    pub frames: Vec<SafeFrame>,
    /// The Sentry UI link.
    pub permalink: String,

    /// Proof that this value came from [`crate::sentry::redact::project`].
    ///
    /// Skipped in serialization so the key set stays exactly the allow-list.
    ///
    /// `pub(super)`, not `pub(crate)`: the point of the token is that a
    /// `SafeIssue` cannot be built outside this module tree, and a field the
    /// whole crate can name is a field the whole crate can fill.
    #[serde(skip)]
    pub(super) scrubbed: Scrubbed,
}

/// A zero-sized token only the `sentry` module tree can mint.
///
/// This is the whole enforcement mechanism for "a `SafeIssue` has been
/// scrubbed": the field is private to the `sentry` module tree, so no other
/// module can name it, and therefore no other module can construct the struct
/// it sits in. [`crate::sentry::redact::project`] is the only place that mints
/// one.
///
/// **Do not derive `Default`.** `#[derive(Default)]` on a tuple struct emits a
/// `Scrubbed::default()` that is as public as the type — which was a crate-wide
/// mint for a token whose entire value is being unmintable, and made the
/// paragraph above false. The inner field's `pub(super)` is the only way in,
/// and it is what confines construction to this tree.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Scrubbed(pub(super) ());

/// Why one Sentry issue was not promoted.
///
/// Carried rather than logged-and-dropped so a sweep can report the shape of
/// what it skipped without a second pass, and so the CLI can print a tally
/// that adds up to the number of issues fetched.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Skipped {
    /// Fewer events than `sentry.min_events`.
    TooFewEvents {
        /// What the issue had.
        events: u64,
        /// What was required.
        required: u64,
    },
    /// Fewer affected users than `sentry.min_users`.
    TooFewUsers {
        /// What the issue had.
        users: u64,
        /// What was required.
        required: u64,
    },
    /// The culprit matched a `sentry.ignore_culprits` glob.
    IgnoredCulprit {
        /// The glob that matched.
        pattern: String,
    },
    /// A GitHub issue already carries this issue's marker.
    AlreadyTracked {
        /// The existing GitHub issue number.
        number: u64,
    },
    /// The run hit `sentry.max_per_run`.
    OverCap {
        /// The cap that truncated the sweep.
        cap: usize,
    },
    /// The Sentry issue has no short id, so no durable dedupe marker could be
    /// built for it. Promoting it would recreate it on every later sweep.
    Undedupable,
}

impl std::fmt::Display for Skipped {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooFewEvents { events, required } => {
                write!(f, "{events} events, below min_events={required}")
            }
            Self::TooFewUsers { users, required } => {
                write!(f, "{users} users, below min_users={required}")
            }
            Self::IgnoredCulprit { pattern } => {
                write!(f, "culprit matches ignore_culprits glob `{pattern}`")
            }
            Self::AlreadyTracked { number } => write!(f, "already tracked by #{number}"),
            Self::OverCap { cap } => write!(f, "over max_per_run={cap}"),
            Self::Undedupable => {
                write!(f, "no short id, so it could never be deduplicated")
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counts_parse_from_a_string_or_a_number() {
        let raw = r#"{"shortId":"API-1","count":"1500","userCount":42}"#;
        let issue: RawIssue = serde_json::from_str(raw).expect("parses");
        assert_eq!(issue.count, 1500);
        assert_eq!(issue.user_count, 42);
    }

    #[test]
    fn an_unparseable_count_reads_as_zero_so_it_fails_the_gate() {
        let raw = r#"{"shortId":"API-1","count":"lots","userCount":null}"#;
        let issue: RawIssue = serde_json::from_str(raw).expect("parses");
        assert_eq!(issue.count, 0);
        assert_eq!(issue.user_count, 0);
    }

    #[test]
    fn a_release_parses_from_either_shape() {
        let bare: RawEvent = serde_json::from_str(r#"{"release":"1.2.3"}"#).expect("parses");
        assert_eq!(bare.release.expect("some").version(), Some("1.2.3"));

        let object: RawEvent =
            serde_json::from_str(r#"{"release":{"version":"1.2.3","dateCreated":"x"}}"#)
                .expect("parses");
        assert_eq!(object.release.expect("some").version(), Some("1.2.3"));
    }

    /// The parse is the allow-list, so a payload full of personal data must
    /// deserialize into a struct that has nowhere to put it.
    #[test]
    fn dangerous_event_sections_have_no_field_to_deserialize_into() {
        let raw = r#"{
            "transaction": "GET /users",
            "user": {"email": "someone@example.com", "id": "u-1"},
            "contexts": {"device": {"name": "iPhone"}},
            "extra": {"session": "abc"},
            "request": {
                "cookies": {"session": "s3cr3t"},
                "headers": [["Authorization", "Bearer tok"]],
                "data": {"password": "hunter2"}
            },
            "entries": [
                {"type": "breadcrumbs", "data": {"values": [{"message": "user@example.com"}]}},
                {"type": "exception", "data": {"values": [{"stacktrace": {"frames": [
                    {"filename": "app.rs", "function": "handle", "lineno": 12,
                     "vars": {"token": "Bearer leaked"}}
                ]}}]}}
            ]
        }"#;

        let event: RawEvent = serde_json::from_str(raw).expect("parses");
        assert_eq!(event.transaction.as_deref(), Some("GET /users"));

        // The breadcrumbs entry parsed into an empty husk — its values carry
        // no readable field at all.
        let breadcrumbs = event
            .entries
            .iter()
            .find(|entry| entry.kind == "breadcrumbs")
            .expect("breadcrumbs entry");
        assert_eq!(breadcrumbs.data.values.len(), 1);
        assert!(breadcrumbs.data.values[0].stacktrace.is_none());

        // The exception frame kept file/function/line and nothing else. There
        // is no `vars` field on `RawFrame` for the token to have landed in.
        let frames = &event
            .entries
            .iter()
            .find(|entry| entry.kind == "exception")
            .expect("exception entry")
            .data
            .values[0]
            .stacktrace
            .as_ref()
            .expect("stacktrace")
            .frames;
        assert_eq!(frames.len(), 1);
        assert_eq!(frames[0].filename.as_deref(), Some("app.rs"));
        assert_eq!(frames[0].lineno, Some(12));

        // And the whole thing, re-serialized from what we hold, mentions none
        // of the payload we refused to declare.
        let held = format!("{event:?}");
        for leaked in [
            "someone@example.com",
            "hunter2",
            "s3cr3t",
            "Bearer tok",
            "Bearer leaked",
            "iPhone",
        ] {
            assert!(!held.contains(leaked), "`{leaked}` survived the parse");
        }
    }

    #[test]
    fn issue_metadata_reads_only_type_and_value() {
        let raw = r#"{"shortId":"API-1","metadata":{"type":"TypeError","value":"boom","filename":"secret.rs"}}"#;
        let issue: RawIssue = serde_json::from_str(raw).expect("parses");
        assert_eq!(issue.metadata.kind.as_deref(), Some("TypeError"));
        assert_eq!(issue.metadata.value.as_deref(), Some("boom"));
        assert!(!format!("{issue:?}").contains("secret.rs"));
    }

    #[test]
    fn skip_reasons_read_as_sentences() {
        assert_eq!(
            Skipped::TooFewEvents {
                events: 3,
                required: 10
            }
            .to_string(),
            "3 events, below min_events=10"
        );
        assert_eq!(
            Skipped::AlreadyTracked { number: 42 }.to_string(),
            "already tracked by #42"
        );
        assert_eq!(
            Skipped::OverCap { cap: 10 }.to_string(),
            "over max_per_run=10"
        );
    }
}
